name: azohra_shell-linter

on: [push]

jobs:
  azohra_shell-linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint check, azohra_shell-linter
      uses: azohra/shell-linter@v0.2.0
      #with:
        # path: "src/*.sh"
        # path
        # Optional. Execute lint check on a specific file or folder. Default: .
